# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-07 18:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(unique=True, verbose_name='Category slug')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'verbose_name': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50, verbose_name='name')),
                ('user_email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('user_url', models.URLField(blank=True, verbose_name='website')),
                ('content', models.TextField(verbose_name='comment')),
                ('created', models.DateTimeField(default=datetime.datetime.now, verbose_name='comment created')),
                ('is_approved', models.BooleanField(default=False, verbose_name='comment approved')),
                ('like', models.IntegerField(default=0, verbose_name='Likes')),
                ('dislike', models.IntegerField(default=0, verbose_name='Dislikes')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Comment', verbose_name='parent comment')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('slug', models.SlugField(unique=True, verbose_name='Post slug')),
                ('tease', models.TextField(blank=True, verbose_name='Tease (summary)')),
                ('body', models.TextField()),
                ('draft', models.BooleanField(default=True, verbose_name='Is draft')),
                ('is_comment_allowed', models.BooleanField(default=True, verbose_name='Allowed')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='Date of creation')),
                ('published_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='Date of publication')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='blog.Category')),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True, verbose_name='Tag slug')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(related_name='metategs', to='blog.Tag'),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post', verbose_name='related post'),
        ),
    ]
