# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-08 14:25
from __future__ import unicode_literals

from django.db import migrations
import djorm_pgfulltext.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='search_index',
            field=djorm_pgfulltext.fields.VectorField(db_index=True, default='', editable=False, null=True, serialize=False),
        ),
    ]
