# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-28 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_search_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(verbose_name='Message:'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email:'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user_name',
            field=models.CharField(max_length=50, verbose_name='Name:'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user_url',
            field=models.URLField(blank=True, verbose_name='Website:'),
        ),
    ]
